# Site settings
title: Harriet Dashnow
email: harriet.dashnow [at] mcri.edu.au
description: > # this means to ignore newlines until "baseurl:"
    Bioinformatician and PhD candidate at the Murdoch Childrens Research Institute, Melbourne, Australia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: hdashnow
github_username:  hdashnow

# Build settings
markdown: kramdown
